# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

unless defined?(CHARACTERISTICS_OUTPUT_PATH_PREFIX)
  CHARACTERISTICS_OUTPUT_PATH_PREFIX = "."
end

if defined?(Cucumber)
  CUCUMBER_VERSION = Cucumber::Version.to_s
else
  CUCUMBER_VERSION = CHARACTERISTICS_OUTPUT_PATH_PREFIX.split('/').last
end


TIMING_TOLERANCE = 0.05

require 'pp'

def read_html_output
  begin
    output_file = "#{CHARACTERISTICS_OUTPUT_PATH_PREFIX}/features/characteristics/cucumber_step_characteristics.html"
    puts "Testing - #{output_file}"
    File.open(output_file) { |f| Nokogiri::HTML(f) }
  rescue Errno::ENOENT => e
    puts "Could not find file '#{output_file}'"
    exit
  end
end
